name: springel
version: 1.0.0
description: Elements which following cursor on limit destination, with spring effect.
homepage: http://rasarts.github.io/Springel/
author: Vostrikov Vitaliy <rasart.pro@gmail.com>
dependencies:
  browser: any
transformers:
- $dart2js:
    {'minify':true}