name: springel
version: 1.0.3
author: Vostrikov Vitaliy <rasart.pro@gmail.com>
description: Elements which following cursor on limit destination, with spring effect.
homepage: http://rasarts.github.io/Springel/
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
transformers:
- $dart2js:
    minify: true
