name: springel
version: 1.0.1
description: Elements which following cursor on limit destination, with spring effect.
homepage: http://rasarts.github.io/Springel/
author: Vostrikov Vitaliy <rasart.pro@gmail.com>
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
transformers:
- $dart2js:
    {'minify':true}